version: '3'
services:
  web315:
    container_name: lab315 
    build: .
    volumes:
      - .:/code
    expose:
      - "8000"
    ports:
      - "8000:8000"

#    command: python /code/mySite/manage.py runserver 0.0.0.0:8000
#    command: python TimeTracker/TimeTracker/manage.py runserver 0.0.0.0:8000
    command: >
      sh -c "python TimeTracker/TimeTracker/manage.py migrate &&
             python TimeTracker/TimeTracker/manage.py runserver 0.0.0.0:8000"
